apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: {{.Values.name}}-worker
    component: worker
  name: {{.Values.name}}-worker
  namespace: {{.Values.namespace}}
spec:
  replicas: {{.Values.initialWorkers}}
  selector:
    matchLabels:
      app: {{.Values.name}}-worker
      component: worker
  template:
    metadata:
      labels:
        app: {{.Values.name}}-worker
        component: worker
      name: {{.Values.name}}-worker
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: {{.Values.name}}-worker
              namespaces:
              - {{.Values.namespace}}
              topologyKey: kubernetes.io/hostname
            weight: 1
      containers:
      - args:
        - agent
        volumeMounts:
        - name: dkron-worker
          mountPath: /opt/local/dkron/config
        image: {{.Values.image}}
        name: dkron
        ports:
        - containerPort: 8080
          name: web
          protocol: TCP
        - containerPort: 8946
          name: rpc
          protocol: TCP
        - containerPort: 6868
          name: raft
          protocol: TCP
      serviceAccount: {{.Values.name}}-sa
      terminationGracePeriodSeconds: 3600 # Max wait time for jobs to be finished, then force kill the pod.
      volumes:
      - name: dkron-worker
        configMap:
          name: {{.Values.name}}-worker
