kind: ConfigMap
apiVersion: v1
metadata:
  name: {{.Values.name}}-worker
  namespace: {{.Values.namespace}}
data:
  dkron.yml: |-
    kubernetes: true
    retry-join: ["provider=k8s namespace={{.Values.namespace}} label_selector=\"app={{.Values.name}}-server\""]
    # Uncomment below to set a tag for a worker
    {{- if .Values.tags}}
    tags:
      {{- toYaml .Values.tags | nindent 6}}
    {{- end}}
