apiVersion: v1
kind: Service
metadata:
  name: {{.Values.name}}-server
  namespace: {{.Values.namespace}}
  labels:
    app: {{.Values.name}}-server
spec:
  publishNotReadyAddresses: true
  ports:
  - name: web
    port: 8080
  - name: rpc
    port: 8946
  - name: raft
    port: 6868
  - name: http-metrics
    port: 9102
  clusterIP: None
  selector:
    app: {{.Values.name}}-server
