apiVersion: v1
kind: Service
metadata:
  name: {{.Values.name}}-server-leader
  namespace: {{.Values.namespace}}
  labels:
    app: {{.Values.name}}-server
spec:
  ports:
  - name: web
    port: 8080
  clusterIP: None
  selector:
    app: {{.Values.name}}-server
    leader: "true"
