kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{.Values.name}}-server
  namespace: {{.Values.namespace}}
  labels:
    app: {{.Values.name}}
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list", "patch", "get"]
