kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{.Values.name}}-server
  namespace: {{.Values.namespace}}
  labels:
    app: {{.Values.name}}-server
subjects:
  - kind: ServiceAccount
    name: {{.Values.name}}-sa
    namespace: {{.Values.namespace}}
roleRef:
  kind: Role
  name: {{.Values.name}}-server
  apiGroup: rbac.authorization.k8s.io
